name: "action-yaml-map"
description: |
  This action returns the value of a key in a map of objects.
  If the key does not exist, it will fail.
inputs:
  map:
    description: |
      map of objects (yaml)
    required: true
  key:
    description: "key of map"
    required: true
  fail:
    description: "true|false"
    required: false 
    default: "true"
outputs:
  status: # id of output
    description: "status: ok|fail"
  value: # id of output
    description: "example: value of map"
runs:
  using: "node20"
  main: "dist/index.js"
